CanQueueAfterDisconnect: false
LobbyQueueMinPlayersCooldown: 120
LobbyQueueHalfPlayersCooldown: 30
LobbyQueueFullPlayersCooldown: 10
GameCountdownAnnouncementsInterval: 15
PreparingPhaseDuration: 5
FinishedPhaseDuration: 15
GameSummary:
  - "<green>============================================"
  - "                     <white>{0}"
  - ""
  - "                  <color:{3}>{1} - {2}"
  - ""
  - "                 <red><bold>1st. <reset><gray>{4} - {5} {10}"
  - "                 <orange><bold>2nd. <reset><gray>{6} - {7} {10}"
  - "                 <yellow><bold>3rd. <reset><gray>{8} - {9} {10}"  
  - "<green>============================================"
GameExplanation:
  Width: 50
  Divisor: "-"
  DivisorColor: "<green>"
  DescriptionColor: "<yellow>"
  GameColor: "<white>"
  